// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU9ICuBtxswDewHH70VUaqKpajVSuz0rQ',
    appId: '1:762155180585:web:bd4800aae7a8e126dab238',
    messagingSenderId: '762155180585',
    projectId: 'airplane-86e88',
    authDomain: 'airplane-86e88.firebaseapp.com',
    storageBucket: 'airplane-86e88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnMbg6_O9ZY4uG4KCWMbc42n_QddJMtlo',
    appId: '1:762155180585:android:e19308980b25bcd5dab238',
    messagingSenderId: '762155180585',
    projectId: 'airplane-86e88',
    storageBucket: 'airplane-86e88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBExqXKgei2js-8mLIwTnqqqUqhCAxatwI',
    appId: '1:762155180585:ios:10162dfa3a4d91d5dab238',
    messagingSenderId: '762155180585',
    projectId: 'airplane-86e88',
    storageBucket: 'airplane-86e88.appspot.com',
    iosBundleId: 'com.example.airplane.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBExqXKgei2js-8mLIwTnqqqUqhCAxatwI',
    appId: '1:762155180585:ios:10162dfa3a4d91d5dab238',
    messagingSenderId: '762155180585',
    projectId: 'airplane-86e88',
    storageBucket: 'airplane-86e88.appspot.com',
    iosBundleId: 'com.example.airplane.RunnerTests',
  );
}
